### ISSUE TITLE
Hi, I've publish a new plugin based on your plugin

### ISSUE THREAD

**Issue by perqin** [leonardosnt/hain-plugin-google#1]
Hi @leonardosnt , inspired by this plugin I fork and modify and publish a similar plugin [hain-plugin-dash](https://github.com/perqin/hain-plugin-dash). I am not familiar with open source license so I hope that I am not violating the rules. Really thank for your works :D

**Comment by leonardosnt** [comment]
No problems :smile: 

Just leave credits please.

**Comment by perqin** [comment]
@leonardosnt I write them at README.md XD

**Comment by leonardosnt** [comment]
@perqin Thanks :smile:
